---
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "labs-nats-cluster"
spec:
  # Number of nodes in the cluster
  size: 3
  version: "1.3.0"

  tls:
    # Certificates to secure the NATS client connections:
    serverSecret: "nats-clients-tls"

    # Certificates to secure the routes.
    routesSecret: "nats-routes-tls"
